### ISSUE TITLE
Preact - TypeScript issue

### ISSUE THREAD

**Issue by jdamon96** [react-dropzone/react-dropzone#1052]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
TypeScript is throwing errors when destructuring `getRootProps()` into a `<div/>` and `getInputProps()` into an `<input/>`

**If the current behavior is a bug, please provide the steps to reproduce.**

  ```
import { render, h, Fragment, FunctionComponent } from "preact";
  import { useCallback } from "preact/hooks";
  import { useDropzone } from 'react-dropzone';
  import "./index.css";
  
  
  interface UploadInterfaceProps {
      // add props here
  }

const UploadInterface: FunctionComponent<UploadInterfaceProps> = (props) => {
    
    const onDrop = useCallback((files: File[]) => {
        files.map(file => {
            console.log(file);
        })
    }, []);

    const { 
        getRootProps,
        getInputProps,
        isDragActive
    } = useDropzone({onDrop, accept: 'audio/*'});
    
    
    return(
        <div>
            <div {...getRootProps()}>
            <input {...getInputProps()} />
            {
                isDragActive ?
                <p>Drop the files here ...</p> :
                <p>Drag 'n' drop some files here, or click to select files</p>
            }
            </div>
        </div>
    )
}
```

The above code returns the following type error for both the `<div>` and `<input>` elements:

destructured `getRootProps()`/`getInputProps()` are not assignable to `HTMLAttributes<HTMLDivElement>`/`HTMLAttributes<HTMLInputElement>` because types of property `contentEditable` are incompatible: type `string | boolean` is not assignable to type `boolean`.

**What is the expected behavior?**
No type error

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
react-dropzone version 11.3.1

**Comment by rolandjitsu** [comment]
@jdamon96 does this happen with React typings as well? Or just Preact?

**Comment by helgardferreira** [comment]
@jdamon96 @rolandjitsu I believe I found the culprit:

[This pull request for the @types/react library](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40658) has introduced a `Booleanish` type that's now sprinkled throughout various interfaces (including `HTMLAttributes`). Whereas the last time the Preact `contentEditable` property of the `HTMLAttributes` interface was updated was 3 years ago.

This is a bit of an awkward situation since the `react-dropzone` library uses the `@types/react` library's type definitions for its type declarations.

Potential solutions could be:

1. To contact the maintainers of the Preact library and propose that they update their type definitions for `HTMLAttributes`, `SVGAttributes`, etc. in accordance with the more recent >16.9 React type definitions.
2. Provide an "escape hatch" by making use of generics for the `DropzoneRootProps` and `DropzoneInputProps` interfaces that default to React's type definitions but can be overridden with Preact's type definitions (you would then also have to update the types for `DropzoneProps` and `DropzoneState` to use generics as well.)

**Comment by mefuru** [comment]
@helgardferreira Did any of the potential solutions work for you?

**Comment by rolandjitsu** [comment]
@jdamon96 @helgardferreira is this still an issue? Do you have a proposal that you think we can implement on our side? If yes, please make a PR.

**Comment by rolandjitsu** [comment]
@helgardferreira I'd assume option 1 would be the best approach (preact should keep their type definitions up to date). So with that in mind, I'll close this. If option 2 is something you seek, please feel free to make a PR with the adjustments.
