### ISSUE TITLE
[BUG] .mov file convert by intself into .gif in safari 15.3

### ISSUE THREAD

**Issue by Unsleeping** [react-dropzone/react-dropzone#1153]
**Describe the bug**
If u put the .mov file into dropzone and log that, u will see that it has .gif extension

ONLY REPRODUCE in safari 15.3

**To Reproduce**
0. Open Safari 15.3
1. Go to https://codesandbox.io/s/smoosh-wave-ckjxc8?file=/src/App.js
2. Click on Dropzone
3. Select file with .mov (maybe with another extensions same problem)
4. See console with .gif file

**Expected behavior**
Expected to get initial extension 

**Screenshots**

<img width="572" alt="Screenshot 2022-03-09 at 13 22 26" src="https://user-images.githubusercontent.com/45426001/157422911-415e9edd-da97-4df5-a8ea-24ea91c59091.png">

<img width="668" alt="Screenshot 2022-03-09 at 13 25 38" src="https://user-images.githubusercontent.com/45426001/157423078-52dbbb2c-f07c-4122-b1f1-acd2f511e482.png">

**Comment by rolandjitsu** [comment]
Interesting. That must be the type that Safari reports because if we'd set it, it would be `video/quicktime` (see [file-selector/src/file.ts#L81](https://github.com/react-dropzone/file-selector/blob/5f42ace2c72bde8371af2318b265bf8ab0dee735/src/file.ts#L81)).

You could easily test it by changing the `getFilesFromEvent` to a custom func and logging the dropped file there.

**Comment by Unsleeping** [comment]
I debugged smth and found that it's not your bug as you said above
add 'video/quicktime' works for me

strange that 'video/*' ignoring video/quicktime
