### ISSUE TITLE
[BUG] Input element not getting set in Chrome

### ISSUE THREAD

**Issue by bvangraafeiland** [react-dropzone/react-dropzone#1208]
**Describe the bug**
The file input element is not getting populated with the selected files in Chrome when using the OS file dialog. This is working properly in Firefox and Safari. When dragging files to the dropzone, it works in none of the browsers, but this is to be expected. #1037 may be related, although no solution was found there.

**To Reproduce**
1. Go to [the basic example](https://react-dropzone.js.org/#section-basic-example)
2. Select any file
3. Disable the `display: none` styling on the input element
4. Firefox/Safari will display the input with the selected file, but in Chrome it'll say "No file chosen"

**Expected behavior**
Behavior should be consistent across browsers.

**Screenshots**
Firefox:
<img width="956" alt="Screenshot 2022-06-09 at 07 47 46" src="https://user-images.githubusercontent.com/3051636/172773579-adc5ac65-1aa6-476a-9ec3-83dcfa944aa0.png">
Chrome:
<img width="949" alt="Screenshot 2022-06-09 at 07 48 07" src="https://user-images.githubusercontent.com/3051636/172773616-ace5a58c-a7b5-449e-abc8-f9ed0177285c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 102.0.5005.61 (Official Build) (x86_64)

**Comment by bvangraafeiland** [comment]
After doing some research myself, I found out that this is due to the default use of the File System Access API. The `showOpenFilePicker` method is not implemented in Safari and Firefox (https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker#browser_compatibility), therefore [this](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L480-L485) piece of codes disables the API. 

In Chrome, the API is available, so the input element is skipped. Is this intended behavior though?

For now, I've fixed it by manually setting `useFsAccessApi` to `false`.

**Comment by danielweil** [comment]
I spent my whole day messing with this problem.

I first noticed in the jest tests, because I used UserEvent to simulate upload to Dropzone, and it added files to the input field.
But when I do it in the browser manually, it does not. I tried messing with fileList but I could not convert a T[] into a FileList to append to the input.

Whem setting useFsAccessApi to false, it does work when selecting from OS prompt, but does not fill the input file field when you dran n' drop a file into the dropzone.

Another issue I had, is how to remove a value from input's fileList param? For now I am using state and disconsidering input dom value, but it would be nice to make it work properly, in order to stay realist to my tests.

**Comment by akmittal** [comment]
> After doing some research myself, I found out that this is due to the default use of the File System Access API. The `showOpenFilePicker` method is not implemented in Safari and Firefox (https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker#browser_compatibility), therefore [this](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L480-L485) piece of codes disables the API.
> 
> In Chrome, the API is available, so the input element is skipped. Is this intended behavior though?
> 
> For now, I've fixed it by manually setting `useFsAccessApi` to `false`.

I think `useFsAccessApi :false` should be default option. I was using this library in [@remix_run](https://github.com/remix-run/remix). Remix form action need `FileList` to get files

**Comment by rolandjitsu** [comment]
The lib does not set files on the input you pass to the dropzone on drop, regardless of using the FS access API or not. The input was/is only required because there's no other way to trigger a file selection programmatically (FS access API provides that now, but it's a draft and may not be implemented at all), and when using the FS access API, the input is only used as a fallback.

You'll need to manage the state outside of the lib, meaning, if you just need FormData, you create it after the files have been dropped/selected in the `onDrop` cb, then you can send that w/ the request to the server (I imagine that's the use case).

**Comment by wpickachu** [comment]
> UserEvent

boom~~~ @[bvangraafeiland](https://github.com/bvangraafeiland)
This helped me a lot. I also spend a whole day to debug this.

**Comment by sharenz** [comment]
For me setting  `useFsAccessApi` to `false` helped only for the filepicker, but not for drag & drop.

I came up with the following solution for Remix:
```ts
const onDrop = useCallback(
    (acceptedFiles: File[]) => {
      const formData = new FormData();

      acceptedFiles.forEach((file) => {
        formData.append("bills", file);
      });
      fetcher.submit(formData, {
        method: "POST",
        encType: "multipart/form-data",
      });
    },
    [fetcher]
  );
```

**Comment by rolandjitsu** [comment]
@bvangraafeiland the file access API is disabled by default now.  @sharenz an example on how to use with forms has been added as well https://react-dropzone.js.org/#section-forms .

I'm going to close this for now.
