### ISSUE TITLE
[BUG] Validator callback doesn't take full File

### ISSUE THREAD

**Issue by adrianbielawski** [react-dropzone/react-dropzone#1234]
**Describe the bug**
According to the type of the validator callback, it should take `file: File` as an argument but on drag enter, all I have is `{kind: 'file', type: 'image/jpeg'}`. Many properties are missing. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Drag a file and enter the drop zone.
2. Try to read `name` or `size` form the `file` argument in validator callback.
3. File has only `kind` and `type` properties.

**Expected behaviour**
All `File` properties are available on file

**Comment by rolandjitsu** [comment]
@adrianbielawski that's a browser limitation. No data is available during drag operations.

**Comment by johnhunter** [comment]
Hmmm. What you describe @adrianbielawski sounds like a `DataTransferItem`. If it is then you should be able to call its `getAsFile` method.

Either way it sounds like the types need to be fixed - maybe raise a PR? 🙂

**Comment by rolandjitsu** [comment]
If you go through https://html.spec.whatwg.org/multipage/dnd.html#dndevents :

<img width="1302" alt="Screenshot 2024-10-07 at 22 55 48" src="https://github.com/user-attachments/assets/d03d13e0-33d3-4f9b-a53e-b1ff445946af">

<img width="1240" alt="Screenshot 2024-10-07 at 22 56 28" src="https://github.com/user-attachments/assets/f6797e07-c5ff-4853-a891-9e1b36bd1014">

You should be able to find that this is the expected behaviour during drag operations that are not `drop` (once you dropped the file/dir).
