### ISSUE TITLE
[BUG] Unable to determine file type onDrop

### ISSUE THREAD

**Issue by joaorr3** [react-dropzone/react-dropzone#1272]
**Describe the bug**
Files with no extension on their title `(image vs. image.png)` don't get their type recognized when used with drag and drop. 
But the same image works if open with the browser dialog.

**To Reproduce**
1. Create a PNG file and make sure it has the *.png* on it's title. `image_1.png`
2. Duplicate that same file and remove the extension from the title: `image_2` ~~.png~~
3. Put a log in the `onDrop` event. 
```js
const { getRootProps, getInputProps, isDragActive } = useDropzone({
    multiple: true,
    onDrop: (f) => console.log(f),
    disabled,
});
```
4. Drop `image_1.png` and you should see something like:
```json
{
    "path": "image_1.png",
    "preview": "blob:http://localhost:3000/2c24fecf-ae41-4a09-a66b-215854d0ee70",
    "lastModified": 1676022561942,
    "name": "image_1.png",
    "type": "image/png"
}
```
5. Now, check that your OS still tags `image_2` as *.png* just to make sure and drop it. You should see something like:
```json
{
    "path": "image_2", // note: no extension
    "preview": "blob:http://localhost:3000/1d2f502e-8c9e-428a-b94f-d5983302cc7f", // diferent id as expected
    "lastModified": 1676022561942,
    "name": "image_2", // note: no extension
    "type": "" // type is empty
}
```
6. Click on the dropzone input to open the browser file dialog and open the `image_2`. You should see:
```json
{
    "path": "image_2.png", // note: with extension
    "preview": "blob:http://localhost:3000/5aad0bfd-203c-41fa-b91e-b52018173bcb", // diferent id as expected
    "lastModified": 1676022561942,
    "name": "image_2.png", // note: with extension
    "type": "image/png"  // type is defined
}
```

**Expected behavior**
Step `5` and `6` should produce the same output as expected.

**Screenshots**
<img width="568" alt="image" src="https://user-images.githubusercontent.com/38807975/218077807-a97a3242-c67f-425d-827d-57bdf35293ae.png">

**Desktop**
 - OS: `macOS 12.5.1`
 - Browser: `Google Chrome Version 110.0.5481.77 (Official Build) (x86_64)` 
 - Version: `react-dropzone@14.2.3`

**Comment by humaidk2** [comment]
This becomes more obvious on macos, cause screenshots on macos don't have extensions in the file name

**Comment by rolandjitsu** [comment]
I'm on macOS 12.7.6 and Chrome 130 and I can see a similar behaviour when using drag or click to select: when no extension is set on the file name, the type is not set:

https://github.com/user-attachments/assets/9dd2cdd9-8e24-49b9-86a9-d832c851bba7

It seems like Chrome cannot tell what kind of file it is if the extension is not set either (it makes sense - parsing a file would probably incur some performance penalty).

To that end, I'll close this as it doesn't look like it's a bug within this lib. But feel free to reopen if you believe otherwise and do provide more context/info so that we can sort out the issue.
