### ISSUE TITLE
[BUG]  drag & drop or select doesn't work on mobile device 

### ISSUE THREAD

**Issue by mahbubhasanhira** [react-dropzone/react-dropzone#1276]

**Comment by iwasrobbed** [comment]
Be sure to see https://github.com/react-dropzone/react-dropzone/issues/1196

especially re: using `open` to handle this on mobile https://github.com/react-dropzone/react-dropzone/blob/master/examples/file-dialog/README.md

**Comment by KutnerUri** [comment]
yes - it's related to the label container. When I replaced the `<label>` with `<div>`, it's now working.
I think there is a fix to prevent duplicated dialogs in windows that misbehaves in mac

**Comment by rolandjitsu** [comment]
@mahbubhasanhira the least you could have done is provide some description in your issue. You get a sample when you open an issue, just fill that in.

@iwasrobbed and @KutnerUri thanks for providing some possible solutions/insight. But without more context on what the author is experiencing, it's difficult to tell what the issue is.

For now, I'm going to close this.
