### ISSUE TITLE
draggedFiles prop on the returned hook (useDropzone) state has been removed - Any alternatives?

### ISSUE THREAD

**Issue by naemtl** [react-dropzone/react-dropzone#1309]
### Discussed in https://github.com/react-dropzone/react-dropzone/discussions/1308

<div type='discussions-op-text'>

<sup>Originally posted by **naemtl** June 12, 2023</sup>
So, as of v14.0.0, `the {draggedFiles} prop on the returned hook state has been removed and the accept/reject state is only computed on drag enter and drop.`

In my project, I made use of the `draggedFiles` prop and would like to know if there's another prop or value that I can use that would offer me the same information. As I understand it, `acceptedFiles` and `fileRejections` props are populated AFTER drag operations, and the `draggedFiles` prop was populated DURING drag operations. Please correct me if I'm wrong. 

Additionally, what was the reason for removing the `draggedFiles` prop?</div>

**Comment by loftshed** [comment]
Just in case anyone else is stuck on this.. for a project I work with, I needed to access the number of dragged files _before_ dropping to display some feedback in our UI accordingly, but ran into this gotcha while working on it.

If you take a look inside a DataTransfer object during a drag event, in my case `onDragEnter`, the logs will show an empty types array **even if this data is actually available**. I was blocked for some time because I didn't bother to actually log the length of the array when I thought it to be empty - instead, I was off on a wild goose chase trying to figure out why it was empty.

```
  const onDragEnter = useCallback((evt) => {
    evt.preventDefault();
    evt.stopPropagation();
    console.log(evt.dataTransfer)
    console.log(evt.dataTransfer.items)
    console.log(evt.dataTransfer.items.length)
  }, []);
 ```
 
When dragging three files, this code logs the following:
 <img width="1038" alt="dropzone" src="https://github.com/react-dropzone/react-dropzone/assets/36140992/a9c9b554-5ad0-44a5-8e3b-505f871e6742">
 
So for another other lost juniors wandering in here.. this is how you can access the data that was previously made available through the `draggedFiles` prop. Hopefully this is helpful to someone out there :)

**Comment by rolandjitsu** [comment]
@naemtl I've responded in https://github.com/react-dropzone/react-dropzone/discussions/1308. Let's continue the discussion there.
