### ISSUE TITLE
Add support for selecting/dropping a directory

### ISSUE THREAD

**Issue by lindblad** [react-dropzone/react-dropzone#134]

**Comment by okonet** [comment]
Hey! Good idea. Do you mind creating a PR for that? If you do, please create it against 4.0 branch and not master.

**Comment by Lakshman-LD** [comment]
Does adding "webkitdirectory" to inputprops allow directory upload

**Comment by Lakshman-LD** [comment]
the input tag for directory upload should be like this 
* <input type="file" id="FileUpload" onchange="selectFolder(event)" webkitdirectory mozdirectory msdirectory odirectory directory multiple />

so , I tried adding inputProps object, overriding the  input Attributes.

      var inputAttributes = {
          type: 'file',
          style: { display: 'none'},
          multiple: true,
          onChange: this.onDrop,
          webkitdirectory: true,
          mozdirectory: true,
          msdirectory: true,
          odirectory: true,
          directory: true
        };

But this doesnt work. Correct me if I am wrong.

**Comment by wdhorton** [comment]
It doesn't work that way because React currently whitelists allow attributes, and webkitdirectory and directory aren't currently whitelisted. See [this issue](https://github.com/facebook/react/issues/3468) for discussion.

**Comment by wdhorton** [comment]
A workaround I'm using until it gets fixed on the React side is to call setAttribute on the input in componentDidMount.

**Comment by rnicholus** [comment]
You don't want to use `webkitdirectory` anyway. One good reason why this file input attribute didn't catch on is that it's potentially dangerous. All files/directories are processed on the UI thread, and this can very easily lock up the browser.

To do this _correctly_ you'll need to make use of the Filesystem API to handle dropped directories, which is a dead W3C spec that only Chrome and Blink-Opera implemented. If a folder is dropped in a Filesystem API-supported browser, the `DataTransfer` object on the drop event will contain an `items` pseudo-array property. Each entry will either be a `FileEntry` or a `DirectoryEntry`. For the latter, you'll need to parse all items in the directory, each of which will be a `FileEntry` or a `DirectoryEntry`, and so on. That's only the tip of the iceberg though. It's quite challenging to handle all of this properly, especially since it is all callback-based (this was implemented before the promise spec) and requires use of the `DirectoryReader` object, which is also non-standard at this point.

**Comment by okonet** [comment]
@rnicholus that's interesting. What do you think of #174?

**Comment by Keepcase** [comment]
+1

I would love to see this feature get implemented.

**Comment by SpencerCDixon** [comment]
Has folder uploading support been added by chance?

**Comment by manodupont** [comment]
So its not released yet ....?

**Comment by leefsmp** [comment]
Is there a way to prevent user to drop a folder? ... I only want to allow dropping files. Thanks btw!

**Comment by CrocoDillon** [comment]
@leefsmp did you figure this out? I also want to prevent dropping folders.

**Comment by puzlpix** [comment]
Great component. Any chance D&D of folders will be completed, or D&D of .zip to folders?

**Comment by Sifogiannos** [comment]
in "onDop" function before "setState" you can check each file object specificly. 
I have seen that in the "File" object, has a propery "size" and "type".

I my Linux (Ubuntu 16.04 and Chrome Version 63.0.3239.108 (Official Build) (64-bit))  i see that the size of a folder item always has the value=4096 and type="", so you might can check for those properties and asume that if a "File" has those values its a folder and do not add it in your setState.

But all this is my asumptions haven't check in on Windows or Mac if the values are the same.
Also you must be careful that if a file does not has extension or has filesize 4096 if will block it too.

Sorry for bad English

**Comment by dejongch** [comment]
Any chance anything happened with this? I could really use the ability to either accept all files in a folder if it is dropped or somehow know it is a folder and not accept it at all.

**Comment by okonet** [comment]
In progress in https://github.com/react-dropzone/react-dropzone/pull/616

**Comment by damianobarbati** [comment]
@leefsmp @CrocoDillon did you find a way to prevent/detect folder dragging? 

In Chrome I always see different sizes for dragged folders (which do not match files in the dragged folder size).

**Comment by damianobarbati** [comment]
@CrocoDillon on Chrome (at least v71.0.3578.98 on MacOS) this can't work because I don't get 4096 as size for dropped folders, be careful!

**Comment by CrocoDillon** [comment]
@damianobarbati interesting, is it a multiple of 4096 by any chance? The SO answer mentions `file.size % 4096 === 0`, worth a shot I guess. If you figure out whether or not this works let me know please :)

**Comment by damianobarbati** [comment]
@CrocoDillon nope, 160 bytes.

<img width="195" alt="screen shot 2019-01-30 at 11 04 10" src="https://user-images.githubusercontent.com/2225869/51973815-cde00280-247e-11e9-93b7-5413e59a53c2.png">
