### ISSUE TITLE
[BUG] type on .md files return an empty string in chrome

### ISSUE THREAD

**Issue by glend1** [react-dropzone/react-dropzone#1368]
**Describe the bug**
when i try to use react-dropzone and try to drop a `.md` file the returned value doesn't contain the correct mime type, it returns an empty string in chrome

**To Reproduce**
```
export default function Page() {
  const printFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    console.log(file);
  };
  const { getRootProps, getInputProps } = useDropzone({
    onDrop: async (acceptedFiles) => {
      console.log(acceptedFiles);
    },
  });
  return (
    <>
      <input type="file" onChange={printFile} />
      <div {...getRootProps()} className="bg-error h-[50px] w-[50px]">
        <input {...getInputProps()} name="upload_files" id="upload_files" />
      </div>
    </>
  );
}
```

**Expected behavior**
i expect the return type value to be `text/markdown`

**Desktop**
 - OS: liinux
 - Browser chrome
 - Version latest

**Comment by Manzn** [comment]
Facing the same bug.

I initially opened an issue in the mantine repository, since i am using the mantine dropzone, but they stated that it is a react-dropzone issue-
[My original issue](https://github.com/mantinedev/mantine/issues/6608)

Everything works fine on Linux, but on Windows it behaves as OP described.

**Comment by rxmarbles** [comment]
@glend1 @Manzn can you provide which specific version of Chrome you are using? `latest` doesn't really help as it could change by the time us maintainers take a look. 

also @Manzn can you provide which version of windows this is being tested through?

**Comment by Manzn** [comment]
@rxmarbles Chrome Version: Version 128.0.6613.138 (Official Build) (64-bit)

**Comment by thea-unique** [comment]
@rolandjitsu 
Colleagues macOS version (where it does not work): 14.6.1 (23G93)
My macOS version (where it works): 14.5 (23F79)

**Comment by malavshah9** [comment]
@thea-unique  @rxmarbles  I can reproduce this issue. But also **I don't think this is the issue relating to react-dropzone**, because I tried using `<input type="file" />` and found that, it is also returning `""` in type for `.md` files. 

Check attached screenshot once:
<img width="1438" alt="Screenshot 2024-10-20 at 2 30 40 PM" src="https://github.com/user-attachments/assets/cfeb3742-8883-42a7-8bb6-cc47faece665">

**Comment by rolandjitsu** [comment]
If the type is not reported by the browser, then [file-selector](https://github.com/react-dropzone/file-selector) should set it based on the file extension, but it seems like it does not 😕

**Comment by rolandjitsu** [comment]
> If the type is not reported by the browser, then [file-selector](https://github.com/react-dropzone/file-selector) should set it based on the file extension, but it seems like it does not 😕

Ah, but the version of file-selector that has the `md` ext is not used 🤦 Gonna bump that. Hopefully it won't cause issues as in the latest stable version we've removed support for es5.

**Comment by rolandjitsu** [comment]
This should go away with https://github.com/react-dropzone/react-dropzone/pull/1392.
