### ISSUE TITLE
[ENHANCEMENT] I want a new feature - Don't check mimeType 

### ISSUE THREAD

**Issue by AJLoveChina** [react-dropzone/react-dropzone#1402]
**Is your feature request related to a problem? Please describe.**

when we want to allow users to select "vsdx" file , we have to set **"application/vnd.ms-visio.drawing": [".vsdx"]**,
but it does not work on mac safari, because mac safari does not understand **application/vnd.ms-visio.drawing**. 

Then we need to add **".vsdx": [""]**, it's working for both chrome and safari, but react-dropzone always print warning message  in console 

`Skipped ".vsdx" because it is not a valid MIME type. Check...`

Source code : 
https://github.com/react-dropzone/react-dropzone/blob/4ca683b9ed7a703661c5eacd0f6ef5e9b90e317f/src/utils/index.js#L217

**Describe the solution you'd like**

React-dropzone should not check the mimeType, as it also mentioned that mimeType is not always reliable. And it's not a job of this library.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by rolandjitsu** [comment]
@AJLoveChina that line of code you referenced is probably not where the issue is. When we say that mime type checks are not reliable we mean the browser checks. It will most likely depend on the browser and how they deal with certain file types.

In fact, `application/vnd.ms-visio.drawing` should be true for `isMIMEType` (see regexr.com/887m9). That function just validates that what you pass is a proper mime type and if not, it'll skip it (which is why you see that warning for the file extension - because we expect a mime type on the left and a list of file extensions on the right).

You could try `"application/*": [".vsdx"]`, but that will probably allow selection of any file that partially meets the mime type criteria.

Perhaps a `noValidation` flag could be useful where you just want to pass a list of things to `accept` and not apply any validation on our end.

**Comment by AJLoveChina** [comment]
@rolandjitsu it makes sense.

But **"application/*": [".vsdx"]**  does not work for safari vsdx file selection.

Finally I find we can't set ".vsdx" into input[accept] attribute without library warnings.

In case someone else happened to the same issue. I want to share my final solution: I am using pnpm, so I did pnpm patch and remove the console.warn in source code.

**Comment by AJLoveChina** [comment]
I created a online jsfiddler to share my test result - https://jsfiddle.net/Baker2/hm86w0ek/

accept=".vsdx" is the best solution

<img width="769" alt="image" src="https://github.com/user-attachments/assets/5f93eda2-6b88-4830-aaa5-fa1d6096ec33">
