### ISSUE TITLE
Erasing File Input value on click

### ISSUE THREAD

**Issue by Austio** [react-dropzone/react-dropzone#226]
Hello,  

First, thanks for the really great project.  This has made our lives alot easier. 

We use redux/redux-form 5.3.3 to manage our state.  So we represent the files as a field object, those fields are tied to inputs.  If the value of that input changes it dispatches a redux event of `redux-form/CHANGE` for the field that was associated with that input.

What that means for this libraries interaction, is that when someone clicks on a dropzone, it sets the value to null, which erases the value from our store.  We have gotten around this by storing the original value in the components state and using that when needed.

My question is, would it be possible or wanted to remove the erasing the file when dropzone is clicked?   What are your thoughts?  

If acceptable I would be able to write the code and tests for it.

I can also think of several alternatives to removing including
1. store the originalValue and on cancel, set the input value to the originalValue
2. Create an option to react-dropzone that would allow bypassing the always clear function

```
  open() {
    this.fileInputEl.value = null; //this is the line i mean
    this.fileInputEl.click();
  }
```

**Comment by okonet** [comment]
Thanks for opening this one. I'm actually not sure why the erasing is needed. It doesn't make a lot of sense to me since then you choose a new file/s from the dialog box it will set the value.

I'm not the original author of this lib and will need to follow the code to understand this one by id opt for remind this line from the lib and release as a major version to guard in SemVer.

**Comment by Austio** [comment]
@okonet i'm thinking that it is mimicing native browser functionality.

If you add a file input to chrome html page
`<input type="file" name="document">`

Then follow these steps
Initial value of document

```
$("[name='document']").value
""
```

Select Add and attach a file

```
$("[name='document']").value
"C:\fakepath\File jpeg.jpg"
```

Click to add a document but select cancel

```
$("[name='document']").value
""
```

**Comment by GuillaumeCisco** [comment]
I'm also concerned by this behavior.
Let's put a multiple select in a page. A user can select one or multiple files with a first action.
With a second action, he should be able to add one or multiples files to the current added files, but currently, files are overwritten.
It is really annoying, I've just spent 3 hours on this issue, thinking it was related to another code part.
Do we have further information about the "cancel" click option as @Austio told about.
I don't really know how to handle it :S

**Comment by GuillaumeCisco** [comment]
Reading W3C RFC : http://w3c.github.io/html/sec-forms.html#file-upload-state-typefile
```
Unless the multiple attribute is set, there must be no more than one file in the list of selected files.

If the element is mutable, then the element’s activation behavior is to run the following steps:

If the algorithm is not allowed to show a popup, then abort these steps without doing anything else.
Return, but continue running these steps in parallel.
Optionally, wait until any prior execution of this algorithm has terminated.
Display a prompt to the user requesting that the user specify some files. If the multiple attribute is not set, there must be no more than one file selected; otherwise, any number may be selected. Files can be from the filesystem or created on the fly, e.g., a picture taken from a camera connected to the user’s device.
Wait for the user to have made their selection.
Queue a task to first update the element’s selected files so that it represents the user’s selection, then fire a simple event that bubbles named input at the input element, and finally fire a simple event that bubbles named change at the input element.
If the element is mutable, the user agent should allow the user to change the files on the list in other ways also, e.g., adding or removing files by drag-and-drop. When the user does so, the user agent must queue a task to first update the element’s selected files so that it represents the user’s new selection, then fire a simple event that bubbles named input at the input element, and finally fire a simple event that bubbles named change at the input element.

If the element is not mutable, it has no activation behavior and the user agent must not allow the user to change the element’s selection.
```
If I understand what it is written here. We should be able to add/remove files.
Furthermore, clicking the 'Cancel' button should not set the value to `null`

**Comment by okonet** [comment]
I think the proper way would be having the state decoupled from the `input` element so we don't rely on the browser implementation since it can be inconsistent + introducing a prop that reflect the mutability of it. So, basically, I'd suggest re-implementing the algorithm. We should ensure that the local component state is always in sync with the input state as well. Thought?

**Comment by Austio** [comment]
@okonet i like that, looks like we are all busy but if i get a couple hour opening at night will whip up a PR for this.

**Comment by okonet** [comment]
@Austio awesome! The benefit of doing it that way is also the testability. So, please don't forget to include tests.

**Comment by maxefi** [comment]
Any progress on this guys?)

**Comment by sunshinesanty** [comment]
Thank you this awesome component, makes life a lot easier. but this issue of not able to clear the input field on click is hitting us hard when we are using it on mobile devices using Windows phone 8.0 , I know this is legacy OS but still is supported within our organization.
The issue is with IE 11 and below, when we upload a file and choose camera to take a photo and upload, the users can upload the first photo, but the subsequent one can only be be done after we select some other file.
This is since the camera always outputs photo with the same name.
Any ideas, hints, suggestions will help a long way.

Thank you.
