### ISSUE TITLE
Introduce Flow types

### ISSUE THREAD

**Issue by okonet** [react-dropzone/react-dropzone#339]
Use Flow types Instead of propTypes and export them for better completion support.

**Comment by okonet** [comment]
@ryyppy do you want to help me this one?

**Comment by pcgilday** [comment]
@okonet - Is anyone already working on this? I'm happy to do this if help is still wanted.

**Comment by okonet** [comment]
#344 might be outdated but I'm still interested in merging it so after #468 is done, I'd love some help on this.

**Comment by SpainTrain** [comment]
Have you considered adding defs to `flow-typed` rather than exporting (<https://github.com/flowtype/flow-typed/tree/master/definitions/npm>)?  The main benefit is that `flow-typed` definitions are scoped to `flow` versions.  This allows a library consumer to move to a new `flow` version before its library(ies) do and vice versa.  Otherwise, as an app developer, it is quite possible to get stuck where you either cannot upgrade your libraries or cannot upgrade `flow` due to version conflicts.

It is also easy to get started with `flow-typed` definitions because `flow-typed` will stub out libraries when installed.  If this option sounds interesting, we could start to flesh out our stubs and open PRs on <https://github.com/flowtype/flow-typed/tree/master/definitions/npm>

**Comment by okonet** [comment]
@SpainTrain what's the process for that? Can you help us with that?

**Comment by ekropotin** [comment]
> There is a definition for react-dropzone in flow-typed now: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-dropzone_v4.x.x/flow_v0.53.x-/react-dropzone_v4.x.x.js.

There are types for version 4.x while the recent version on NPM is 7.0.1.

**Comment by rolandjitsu** [comment]
@TLadd I understand. I wonder if it would be difficult to have both TS and Flow types in the same repo ... Do you have any idea if this is possible at all?

**Comment by TLadd** [comment]
Sure, it would have to be this repo though (the ts definition is already here: https://github.com/react-dropzone/react-dropzone/blob/master/typings/react-dropzone.d.ts). The other option is to update flow-typed. Just depends on if the react-dropzone maintainers want to have them here or not. Obviously makes it easier to ensure the types are kept up to date, but adds a maintenance cost.

**Comment by rolandjitsu** [comment]
@TLadd I am a maintainer 😄 But I plan on moving the current code to TS, which means the TS typings that currently are separate will be gone. So I'm not sure how the flow types would work with the new TS code 😕

**Comment by okonet** [comment]
Alternatively we could try reason and generate types from it. I know people who could help us with that. Is there an interest?

**Comment by SpainTrain** [comment]
I would like to reiterate the significant benefit of using flow-typed rather than having definitions in the npm package (https://github.com/react-dropzone/react-dropzone/issues/339#issuecomment-338329809) - libdefs are scoped to a compatible range of flow versions.  This is critical for a library consumer while flow is still pre-1.0 and in flux.  Another benefit I didn't mention previously is that the flow-typed maintainers are very helpful in PRs for improving types defs and adding tests.  

Regarding having both ts and flow defs, this is very doable and somewhat common.  For a basic example of this, check out react-with-separator.  Below is a link to a ts project that I ported to flow-typed, which required very little change.  While this example uses a ts def file, the porting process is the same whether the source is native ts or uses a def file because flow-typed generates its stubs from the transpiled javascript.  For less trivial examples, AFAIK most of the major ecosystem libs have defs for both (e.g., Redux, etc.).

- react-with-separator (ts) https://github.com/LinusU/react-with-separator/blob/master/index.d.ts
- react-with-separator (flow) https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-with-separator_v1.x.x/flow_v0.72.x-/react-with-separator_v1.x.x.js

I am not actively using dropzone but may be in the near future, at which point I will go ahead and add defs to flow-typed if they aren't yet there (I find it *much* easier to type a lib I am actively using than attempting to do so cold).

**Comment by rolandjitsu** [comment]
I will close this issue as it's just lingering here and it doesn't seem like anyone will work on it anytime soon. If anyone would like to add support for flow types within this repo, please make a PR.
