### ISSUE TITLE
safari 10.1: File dialog not open by onClick event

### ISSUE THREAD

**Issue by izadmehr** [react-dropzone/react-dropzone#522]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
By clicking the dropzone on Safari 10.1, the select file dialog not open. 
**If the current behavior is a bug, please provide the steps to reproduce.**
1. click on the dropzone on Safari 10.1

**What is the expected behavior?**
File dialog opens

I think it's related to this: `style: { display: 'none' }`. Is it better to remove it and add a parent with this style to it?

```
.hiddenParent {
 width: 0px;
 height: 0px;
 overflow: hidden;
}
```

**Comment by izadmehr** [comment]
As I found out the only way to fix this is using a label with for attribute. This label should be the parent of the children. By this change, there is no need to triggering the click event manually.

**Comment by Ctaque** [comment]
I have the same issue on google chrome. The onClick event is working, but the dialog is not opening.
 It's woking in Firefox.
OS: Archlinux, Google chrome Version 55.0.2883.87 (64-bit)
react-dropzone version 4.2.3

**Comment by pdomaleczny** [comment]
Hey, I am also having this issue on Safari 10.X version. Despite that it works on all browsers. I am using react-dropzone with 4.2.0 version

**Comment by libasoles** [comment]
Could you please guys try the demos in the page to confirm if it also happens there?
https://react-dropzone.netlify.com/#proptypes

I'm using v4.2.1, and it works great in linux. But my client reports that when he opens the dialog in chrome, it scrolls to the top of the page. I have no way to reproduce that.

**Comment by zwallacedev** [comment]
For anyone having trouble with this... I was having trouble determining why my iOS was not responding to touch events. It turns out that the original dropzone package that this was forked from only handles click events, but does not handle touch events. To enable these touch events as click events, you need to add the `needsclick` CSS class to your code.

Example:
```
import 'react-dropzone'
<Dropbox className="needsclick" onDrop={() => someFunction}/>
```

Not entirely sure if this is related to @libasoles , but I believe this could help the original post. Here is the original post I found discussing this issue: https://github.com/enyo/dropzone/issues/935

**Comment by d33con** [comment]
I've got some strange behaviour here. In my app the file upload box opens and drag and drop works in Chrome and Edge but not in Firefox 60.0. However the examples page does work with drag and drop and file dialog box in Firefox.

I'm using 4.2.9

Any ideas?
