### ISSUE TITLE
the latest version of chrome stopped working method  onDrop

### ISSUE THREAD

**Issue by vshvydky** [react-dropzone/react-dropzone#539]
Error code 0 message:
"The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired."
chrome version: 62.0.3202.94

**Comment by rkmarks** [comment]
@vshvydky I was unable to duplicate this issue using the examples from https://react-dropzone.js.org/ on my chrome browser w/ that version. can you provide the code you are using to duplicate this issue?

**Comment by jianliangzhao** [comment]
The drag & drop from file system stopped working for me completely. I am running Chrome `Version 62.0.3202.94 (Official Build) (64-bit)` on Mac High Sierra 10.13

**Comment by rkmarks** [comment]
@jianliangzhao hmm i won't be able to test that. Can you provide further details/errors/logs of events to show that they are not firing?

**Comment by okonet** [comment]
I just tested with `Version 63.0.3239.84 (Official Build) (64-bit)` on High Sierra and everything works as expected.

**Comment by okonet** [comment]
Unless reproducible example is added, I consider this is not an issue.

**Comment by php4518** [comment]
Hello, I am using react-email-editor and react-dropzone in the same project. my first page contains react-dropzone and another contains react-email-editor. Initially, when I drag and drop the file in react-dropzone, it works completely fine. once I drag component for email-editor, react-dropzone doesn't take dragged files. here is the demo.
https://codesandbox.io/s/x39wxnx5lz

the issue is only with chrome in Mac OS. works fine with firefox, safari, and opera.

**Comment by rolandjitsu** [comment]
@php4518 please open a new issue, describe what the problem is and provide some way to reproduce it.
