### ISSUE TITLE
convert blob url to base64. i mean i need base 64 for upload it to firebase.

### ISSUE THREAD

**Issue by erkeElzhan** [react-dropzone/react-dropzone#650]
Please help me

**Comment by rkmarks** [comment]
@erkeElzhan you should be able to override the `onDrop` function of the dropzone to be able to convert your files to base64. doing a simple google search i came upon this https://stackoverflow.com/questions/18650168/convert-blob-to-base64/42038379. I am closing this issue for now since this is more of needing help than an actual issue.
