### ISSUE TITLE
Edge: drag and drop doesn't work properly from Open dialog

### ISSUE THREAD

**Issue by slikts** [react-dropzone/react-dropzone#745]
- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**

Dragging and dropping files from the Open dialog makes the dropped files register only after the Open dialog is closed.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open dialog 
1. Drag file from dialog to drop zone
1. Dropped file doesn't register
1. Close dialog
1. Dropped files now show up

**What is the expected behavior?**

The dropped files should show at the time they're dropped like in other browsers (tested in Chrome, Firefox).

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**

Edge 42.17134.1.0
react-dropzone 8.0.3

#725 may be a related PR.

**Comment by rolandjitsu** [comment]
@slikts while dropping files from the file dialog is allowed, it is a weird thing to do.

The expected behaviour is that you select the files and just hit the open button (or whatever is called) of the file dialog. Or you drag and drop from a file explorer window onto the dropzone area.

I think that the drag events are not triggered while the file dialog is opened (each browser may behave differently) and I'm afraid that there isn't much that we can do to change that.

**Comment by slikts** [comment]
The behavior works in other libraries with Edge, so it's possible technically. This has been discussed in the issues linked to #725 (like #723), the take-away being that users don't differentiate between file explorer windows and open dialogs. #725 specifically enables this behavior, but appears to have missed Edge, so I'd urge you to reopen this issue. I'll look to try to make a PR for it shortly.

**Comment by rolandjitsu** [comment]
@slikts feel free to make a PR.
