### ISSUE TITLE
Drag & Drop doesn't work on IE 11

### ISSUE THREAD

**Issue by taikn** [react-dropzone/react-dropzone#776]
**Do you want to request a *feature* or report a *bug*?**

- [x ] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Unable to drop files into the dropzone on IE 11
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Try dropping some files into the dropzone on IE11
2. `Unhandled promise rejection TypeError: Can't call method on  undefined` appears in console

**What is the expected behavior?**
Expected to be able to get dropped files

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Windows 10, IE 11, react-dropzone 10.0.0

**Comment by rolandjitsu** [comment]
Will investigate and let you know if this is an issue on our side.

**Comment by rolandjitsu** [comment]
Sorry, I cannot seem to be able to test this on SauceLabs and I do not have a Windows machine. Could you pinpoint where the problem happens and what is your current setup (some code sample or reproducible example on codesandbox).

**Comment by taikn** [comment]
I am using dropzone the way described in the docs (hook). The same behaviour can be seen, when opening https://react-dropzone.js.org in IE11 and trying any of the examples listed there (eg. one with Previews).

**Comment by bcobra** [comment]
i was able to get it to work downgrading to 8.0.4. There seems to be an issue with the drop effect =copy on the newest version causing a promise rejection if i remember correctly

**Comment by rolandjitsu** [comment]
There are definitely some problems with some of the examples (APIs that are not supported in IE11), but I'm not sure what the problem is with the drag events, I will try again on SL, maybe I'll manage to replicate the problem.

**Comment by jinguenee** [comment]
The same situation.

I think dropEffect issue

**Comment by rolandjitsu** [comment]
One thing to note is that [file-selector](https://github.com/react-dropzone/file-selector) makes use of [Array.from()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) which needs to be polyfilled in IE11.

Besides that, I'm having some trouble testing drag 'n' drop behavior on SauceLabs (cannot drag drop anything, anywhere). Could use some help from someone who has a Windows machine and IE11, because it probably has nothing to do with `dropEffect`.

**Comment by taikn** [comment]
This seems to be the related to `file-selector`. Please see here: react-dropzone/file-selector/issues/9

**Comment by jsm174** [comment]
With this new release I am now getting:

```
TypeError: getRootProps is not a function

  118 |    {({ getRootProps, getInputProps }) => (
> 119 |       <div className="file-input-field-default" {...getRootProps()}>
```

I didn't see anything in readme that suggests this should now be done in a different way?

Reverted back to 10.0.0.

**Comment by HemalR** [comment]
Not sure if this is the same issue or different, I upgraded my package to 10.1.10 and IE 11 stopped working. I upgraded a few packages at once so not 100% sure this is the package, but FWIW, the demo site: https://react-dropzone.js.org/ does not work on IE-11.

(I agree with what everyone is thinking, IE is a cancer that really needs to go away!!).

Anyway, I've set up a VM on Azure to test this out, I have a couple of screenshots below. Happy to help if I can in any way?

Is the demo site running the latest version?

![image](https://user-images.githubusercontent.com/15634303/69712012-07d07280-113d-11ea-9829-b0b90490be05.png)

Source file is a minified version, but I believe an arrow function may be the issue here: 

![image](https://user-images.githubusercontent.com/15634303/69712073-2c2c4f00-113d-11ea-9302-19c21038c8a6.png)

**Comment by rolandjitsu** [comment]
It's possible you're missing some polyfills as we recently made a release which removed the core-js import.

**Comment by HemalR** [comment]
My issue ended up going away after upgrading this to: 10.2.1 (but I also upgraded another package that was also showing IE incompatibility, so unsure whether react-dropzone was ever the cause).

That said, the demo site itself, as per the above, does not load on IE. Perhaps it is using an old version of the package?

**Comment by rolandjitsu** [comment]
> My issue ended up going away after upgrading this to: 10.2.1 (but I also upgraded another package that was also showing IE incompatibility, so unsure whether react-dropzone was ever the cause).
> 
> That said, the demo site itself, as per the above, does not load on IE. Perhaps it is using an old version of the package?

Please open a new issue describing the issue in IE.
