### ISSUE TITLE
Make it possible to remove file from acceptedFiles state

### ISSUE THREAD

**Issue by claytonfbell** [react-dropzone/react-dropzone#805]
**Do you want to request a *feature* or report a *bug*?**

- [ ] I found a bug
- [x] I want to propose a feature

**What is the current behavior?**
No way to remove file from the acceptedFiles state array.

**If this is a feature request, what is motivation or use case for changing the behavior?**
it would be nice to allow user to remove files with a trash button from the acceptedFiles state array. Please forgive me if this functionality exists, I did not find it in examples or StackOverflow and I'm still learning to work with hooks.

**Comment by rolandjitsu** [comment]
@claytonfbell I think this is out of the scope of dropzone. It's up to you to alter the files in whatever way you need/want.

Furthermore, the dropzone can be used as a headless component or a hook, meaning there is no UI rendered, therefore, we cannot add any delete buttons. You're perhaps referring to the examples, but note that those are not part of the dropzone lib.

If you have further issues, feel free to report it.

**Comment by claytonfbell** [comment]
I see, thanks for getting back. I missed the response until now.

I didn't mean to propose adding any UI component. But I want to mutate the `acceptedFiles` state array that is returned from the `useDropzone` hook. Like if we added a `clearFiles` function that could also be returned from the hook. The "Clear" UI button on my component's end would call it `onClick={clearFiles}`.

````JavaScript
    // line 743 - added function to useDropdown's return
    clearFiles: () => {
      dispatch({ type: 'setFiles' , acceptedFiles: [], rejectedFiles: []})
    }
````

Maybe I'm missing an obvious way to change the state of "acceptedFiles" returned from the hook.

Thank you, this is a terrific library.

**Comment by rolandjitsu** [comment]
@claytonfbell this can be done in the user land, or maybe I'm missing something 😕 It could help if you could provide an example illustrating your use case.

**Comment by claytonfbell** [comment]
Thank you again!

I've taken the existing **Basic** example and added a **Remove File** button next to each file, as well as the addition of a **Remove All** button.

![dropzone](https://user-images.githubusercontent.com/3332575/55499865-dd550680-55fb-11e9-8c03-7382fa245cc9.gif)

```JavaScript
import React from 'react';
import {useDropzone} from 'react-dropzone';

function Basic(props) {
  const {acceptedFiles, getRootProps, getInputProps, inputRef} = useDropzone();

  const removeFile = (file) => () => {
    console.log('removeFile...')
    acceptedFiles.splice(acceptedFiles.indexOf(file), 1)
    console.log(acceptedFiles)
  }

  const removeAll = () => {
    console.log('removeAll...')
    acceptedFiles.length = 0
    acceptedFiles.splice(0, acceptedFiles.length)
    inputRef.current.value = ''
    console.log(acceptedFiles)
  }

  const files = acceptedFiles.map(file => (
    <li key={file.path}>
      {file.path} - {file.size} bytes <button onClick={removeFile(file)}>Remove File</button>
    </li>
  ));

  return (
    <section className="container">
      <div {...getRootProps({className: 'dropzone'})}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{files}</ul>
      </aside>
      { files.length > 0 && <button onClick={removeAll}>Remove All</button> }
    </section>
  );
}

export default Basic

```

**Comment by claytonfbell** [comment]
After working with this more I work around by creating my own `useState`. Not sure if this is the best way, but maybe this can be helpful to others.

```
import React, { useState, useCallback } from "react"
import { useDropzone } from "react-dropzone"

function Basic(props) {
  const [myFiles, setMyFiles] = useState([])

  const onDrop = useCallback(acceptedFiles => {
    setMyFiles([...myFiles, ...acceptedFiles])
  })

  const { getRootProps, getInputProps } = useDropzone({
    onDrop,
  })

  const removeFile = file => () => {
    const newFiles = [...myFiles]
    newFiles.splice(newFiles.indexOf(file), 1)
    setMyFiles(newFiles)
  }

  const removeAll = () => {
    setMyFiles([])
  }

  const files = myFiles.map(file => (
    <li key={file.path}>
      {file.path} - {file.size} bytes{" "}
      <button onClick={removeFile(file)}>Remove File</button>
    </li>
  ))

  return (
    <section className="container">
      <div {...getRootProps({ className: "dropzone" })}>
        <input {...getInputProps()} />
        <p>Drag 'n' drop some files here, or click to select files</p>
      </div>
      <aside>
        <h4>Files</h4>
        <ul>{files}</ul>
      </aside>
      {files.length > 0 && <button onClick={removeAll}>Remove All</button>}
    </section>
  )
}

export default Basic

```

**Comment by gundojuprashanth** [comment]
Hi
I am using default rejected files from the dependency. I need to remove the rejected file, can you please explain me

[dropzone.txt](https://github.com/react-dropzone/react-dropzone/files/3466809/dropzone.txt)

**Comment by cbrwizard** [comment]
Imo, this should be a part of package api.

**Comment by aimdevlee** [comment]
I hope this example will be helped (Used DataTransfer API)

[![Edit Removable drop zone](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/removable-drop-zone-82km9?fontsize=14&hidenavigation=1&theme=dark)

**Comment by aderaHenry** [comment]
@claytonfbell , thank you.

**Comment by aaj** [comment]
Is there really no built-in way of doing this?

**Comment by rolandjitsu** [comment]
@aaj no. But seeing that more ppl want this, I think someone should make a PR as I don't have the time to do it.

**Comment by aaj** [comment]
@rolandjitsu After writing that comment I figured out a way to do it in my own code, and honestly I've changed my mind about this. `acceptedFiles` is only available during the `onDrop` callbacks. It doesn't represent a persistent list of selected files, so it doesn't really make sense to have a way of clearing that list. I essentially did what @claytonfbell did, which is the only logical way to do it (keeping files in your own state).

**Comment by rcasari1987** [comment]
@claytonfbell , thank you.

**Comment by wmadam** [comment]
> I hope this [example](https://codesandbox.io/s/removable-drop-zone-82km9) will be of some help to you guys (Used DataTransfer API)

This example does not work with dropped files since dropping does not set the files on the input...

**Comment by waldothedeveloper** [comment]
> After working with this more I work around by creating my own `useState`. Not sure if this is the best way, but maybe this can be helpful to others.
> 
> ```js
> import React, { useState, useCallback } from "react"
> import { useDropzone } from "react-dropzone"
> 
> function Basic(props) {
>   const [myFiles, setMyFiles] = useState([])
> 
>   const onDrop = useCallback(acceptedFiles => {
>     setMyFiles([...myFiles, ...acceptedFiles])
>   })
> 
>   const { getRootProps, getInputProps } = useDropzone({
>     onDrop,
>   })
> 
>   const removeFile = file => () => {
>     const newFiles = [...myFiles]
>     newFiles.splice(newFiles.indexOf(file), 1)
>     setMyFiles(newFiles)
>   }
> 
>   const removeAll = () => {
>     setMyFiles([])
>   }
> 
>   const files = myFiles.map(file => (
>     <li key={file.path}>
>       {file.path} - {file.size} bytes{" "}
>       <button onClick={removeFile(file)}>Remove File</button>
>     </li>
>   ))
> 
>   return (
>     <section className="container">
>       <div {...getRootProps({ className: "dropzone" })}>
>         <input {...getInputProps()} />
>         <p>Drag 'n' drop some files here, or click to select files</p>
>       </div>
>       <aside>
>         <h4>Files</h4>
>         <ul>{files}</ul>
>       </aside>
>       {files.length > 0 && <button onClick={removeAll}>Remove All</button>}
>     </section>
>   )
> }
> 
> export default Basic
> ```

@claytonfbell  doesn't ```useCallback``` requires a dependency array in order to execute? 
[https://reactjs.org/docs/hooks-reference.html#usecallback](react-docs-useCallback)

**Comment by claytonfbell** [comment]
Yes, I’m unsure why that was missing, good catch. I’ve added a dependency array.

**Comment by ijayoa** [comment]
@claytonfbell, thanks... thanks.. thank you!

**Comment by lsandoval0000** [comment]
@claytonfbell Thanks sir.

**Comment by madisonbullard** [comment]
Tracking the file list using local state works in most cases, but because the local state isn't tied to the `<input>`'s `value` attribute (a `FileList`), removing a file from local state does not remove the file from the `<input>`. So when I add a file, "remove" it (from local state), and then try to add the same file again, `onDrop` does not fire because the file is already present in the `<input>`'s `FileList`.

I am unsure how to fix this bug without a helper method allowing me to clear/reset the `<input>`

**Comment by simonbarker** [comment]
> I hope this [example](https://codesandbox.io/s/removable-drop-zone-82km9) will be of some help to you guys (Used DataTransfer API)

This is the approach that solved this for me, I was uploading files to a server in a `useEffect` based on `acceptedFiles` changing, there were other dependencies to this `useEffect` and when they changed it would re-upload the files! Moving to an intermediate local state 'buffer' of `filesToUpload` and then clearing that in the post requests `.then()` and `.catch()` block solved this problem.

Ideally it would have been nice to have just done `setAcceptedFiles([])` but the above worked well

**Comment by Crocsx** [comment]
Yeah, having to make a secondary state to handle the same thing that is already handled by the library should be only a temporary solution. An API method would be great in the future. Thanks

**Comment by meglio** [comment]
Now that we see how many people are trying to work around it, it's clear that being able to remove files from the list should be part if API. The main issue here is that the original `<input>`s list of files is not updated. So the API would allow to do that.

**Comment by ferso** [comment]
```
  const onDropAccepted = (files: any) => {
    setFiles(files);
  };
  let {
    getRootProps,
    getInputProps,
    isDragActive,
    isDragAccept,
    isDragReject,
  } = useDropzone({ accept: "image/*", multiple: true, onDropAccepted });


```

**Comment by meglio** [comment]
Turns out it's easier to implement a component from scratch than to wait for all the fixes to happen :)

<img width="277" alt="image" src="https://user-images.githubusercontent.com/282177/141033595-4efa1900-f168-4579-ab7d-6f57a4828b1b.png">

By this I just wanted to say to all those who find the react-dropzone not enough - you can do it! It just took me half a day to build the component that you can see in the screenshot above. Features:

- configurable max number of files, max file size, file types, etc
- rename files before uploading
- remove files individually
- preview for images
- file size displayed for each file
- drag&drop one or multiple files
- indicate visually if a file is bigger than permitted

Hope react-dropzone can adapt some of these features ;)

**Comment by rodolphoasb** [comment]
@meglio the UI/UX looks awesome could you please share the repo of this component?

**Comment by meglio** [comment]
@rodolphoasb it would be a pleasure for me to do so, but it's tighthly integrated into the proprietary CRM I'm working on, so it's not a separate repo. I just wanted to make sure people understand it is easy and super quick to build your own, and encourage them to do so.

**Comment by daskon** [comment]
> Thank you again!
> 
> I've taken the existing **Basic** example and added a **Remove File** button next to each file, as well as the addition of a **Remove All** button.
> 
> ![dropzone](https://user-images.githubusercontent.com/3332575/55499865-dd550680-55fb-11e9-8c03-7382fa245cc9.gif)
> 
> ```js
> import React from 'react';
> import {useDropzone} from 'react-dropzone';
> 
> function Basic(props) {
>   const {acceptedFiles, getRootProps, getInputProps, inputRef} = useDropzone();
> 
>   const removeFile = (file) => () => {
>     console.log('removeFile...')
>     acceptedFiles.splice(acceptedFiles.indexOf(file), 1)
>     console.log(acceptedFiles)
>   }
> 
>   const removeAll = () => {
>     console.log('removeAll...')
>     acceptedFiles.length = 0
>     acceptedFiles.splice(0, acceptedFiles.length)
>     inputRef.current.value = ''
>     console.log(acceptedFiles)
>   }
> 
>   const files = acceptedFiles.map(file => (
>     <li key={file.path}>
>       {file.path} - {file.size} bytes <button onClick={removeFile(file)}>Remove File</button>
>     </li>
>   ));
> 
>   return (
>     <section className="container">
>       <div {...getRootProps({className: 'dropzone'})}>
>         <input {...getInputProps()} />
>         <p>Drag 'n' drop some files here, or click to select files</p>
>       </div>
>       <aside>
>         <h4>Files</h4>
>         <ul>{files}</ul>
>       </aside>
>       { files.length > 0 && <button onClick={removeAll}>Remove All</button> }
>     </section>
>   );
> }
> 
> export default Basic
> ```

thanks. it works for my nextjs app

**Comment by pedegago** [comment]
> Tracking the file list using local state works in most cases, but because the local state isn't tied to the `<input>`'s `value` attribute (a `FileList`), removing a file from local state does not remove the file from the `<input>`. So when I add a file, "remove" it (from local state), and then try to add the same file again, `onDrop` does not fire because the file is already present in the `<input>`'s `FileList`.
> 
> Because `onDrop` doesn't fire, the file does not get added back to my local state.
> 
> I am unsure how to fix this bug without a helper method allowing me to clear/reset the `<input>`
> 
> EDIT: I resorted to unmounting and remounting the `<input>` when user removes the file. That gives us a fresh input to work with, which will accept the original file without issues
> 
> ```ts
>   const [isInputMounted, setIsInputMounted] = useState(true);
>   useEffect(
>     function remountInput() {
>       if (!isInputMounted) {
>         setIsInputMounted(true);
>       }
>     },
>     [isInputMounted]
>   );
> 
>   function handleRemoveFile() {
>     setIsInputMounted(false);
>     setFile(null);
>   }
> 
>   const { getRootProps, getInputProps, inputRef } = useDropzone({
>     onDrop,
>   });
> 
>   return (
>     <div>
>       {isInputMounted && (
>         <input
>           {...getInputProps({
>             name,
>           })}
>           data-testid="InputFileUploadField_input"
>         />
>       )}
>     </div>
>   )
> ```

Same situation... but instead of your code i just add a `key` prop to my `input` this way: `<input key={files} {...getInputProps()} />` where files is my array of files in my local state. I hope this helps to everyone.

**Comment by moods-72** [comment]
Thank you @claytonfbell.

**Comment by lucashfreitas** [comment]
Since acceptedFiles is a state provided by `useDropzone` I thinkit should offer a callback to mutate that state stead of manually `splicing` the object? Since we are doing this we are losing the acceptedFiles as a single source of truth. Would a PR be welcome @claytonfbell ?

**Comment by replaysMike** [comment]
why was this closed lol

**Comment by cjauvin** [comment]
I need to allow the user to remove "accepted files", which seems, as discussed above, a relatively common use case (which is implemented by upstream libraries like MUI Dropzone, based on this one).

As my understanding of the code is too limited, I'm on the fence about the need to include it in the official API, however, I would think that having an example such as the one provided by @claytonfbell, above, would be a readlly helpful addition to the docs.

**Comment by meglio** [comment]
> Sorry but I'm going to make up some noise on 2025 new years.

With all due respect, it is a tiny smiley "hahaha" moment. How much time passed... Remember the component I created, see the comment above:

https://github.com/react-dropzone/react-dropzone/issues/805#issuecomment-964702159

It is still working like a charm, zero issues since the inception time. I struggle to understand what makes it so long and so frustrating for people to implement things and make them work quickly and forever. I abandoned all attempts to use this  react-dropzone component and have been using my own since then. I recommend everyone do the same, only implement features that you need, focus on that, and you'll be done fast, and the component will be small and fast.

**Comment by rolandjitsu** [comment]
> Sorry but I'm going to make up some noise on 2025 new years.
> 
> What is the proper way to do this now to keep state and file input in sync?
> 
> Are you guys still using this library or something else as a sort of "File Manager"?

What is your use case? I'm sure there are plenty of discussions on the topic of keeping the input and files in sync if you search the issues.

**Comment by rolandjitsu** [comment]
> > Sorry but I'm going to make up some noise on 2025 new years.
> 
> With all due respect, it is a tiny smiley "hahaha" moment. How much time passed... Remember the component I created, see the comment above:
> 
> [#805 (comment)](https://github.com/react-dropzone/react-dropzone/issues/805#issuecomment-964702159)
> 
> It is still working like a charm, zero issues since the inception time. I struggle to understand what makes it so long and so frustrating for people to implement things and make them work quickly and forever. I abandoned all attempts to use this react-dropzone component and have been using my own since then. I recommend everyone do the same, only implement features that you need, focus on that, and you'll be done fast, and the component will be small and fast.

@meglio thanks for the impractical comment. Not only that it doesn't really help anyone (since you haven't shared your custom impl. with anyone), but it also goes against the whole reason for having an open source community where everyone can **contribute**.

If you find it more practical to start from scratch, sure, it's your choice and time. But recommending to everyone to do the same in a forum/place where some of us have put in dozens (if not hundreds) of hours of work, just seems discourteous.

So if you do want to share you custom package this time around, I'd appreciate that and I can link to it from this package. Otherwise, please keep these conversations constructive.

**Comment by meglio** [comment]
Your response is appreciated. My sarcasp is partly due to the fact that little to no progress is made in the area that is actually important to the end user(s). While you do bother to spend time to write a long response to my critique, you don't for the main question for a new comer with a bar minimum response such as "I'm sure there are plenty of discussions on the topic of keeping the input and files in sync if you search the issues." - this is what I would consider not constructive, not helpful, as well as discourteous.

Keeping in sync and being able to delete is a common task for a filedrop. If you had a clear solution, you could just link to the documentation. If you don't have the documentation but the is no clear explanation on how to do this and that in your component, then you could write such documentation and link to it. If it still does not work properly and/or there is no clear API to achieve the deletion and synchronisation, and after a year people are still asking about it, then sorry the number of hours you and the contributors put into this does not help - it has no meaning for the user who just came and asked about the same thing a year after the feature was closed with a "I think this is out of the scope of dropzone" comment.

I repsect the effort and the open-sourceness, but I consider your response to the end user's question impractical, that's why I intervened and shared my view / advice that I think is much more practical and helpful - which is, again, "do not wait and do not spend time to convince the library contributors, do your own".

---

Regarding sharing my library, I'd gladly do so, it's just that it is integrated into the application and it only does what is needed in my particular case, so although it does it very well, I'm not sure how I can help/contribute without spending too much time and extractingthe library out of my project and making it fully-featured like yours. Again, I was just saying, it the library can't do what you need, don't wait, make your own - this often proves to be the fastest "solution".

Respectfully,
Anton

**Comment by joshuajaco** [comment]
Just stumbled upon this. I am very confused that this is not part of the API. How do you expect a user to remove a file they accidentally uploaded? Press F5 and reload the entire page? I'm also not sure how this could be reasonably implemented in user land. Not only would we need to duplicate the state we also somehow need to remove the file from the `<input>`.

**Comment by evgenii-scenthound** [comment]
My solution to reset state that also clear all internal state. Feel free to use:

```
const { inputRef } = useDropzone()

inputRef.current.value = null
inputRef.current.dispatchEvent(new Event('change', { bubbles: true }))
```

**Comment by meglio** [comment]
In my component, I handle all file addition and removal manually. Here are extracts from the component if that helps:

```jsx
const file_input_ref = useRef(null);
const [files, set_files] = useState([]);

// ...

    const handle_remove_file = (file_ind) => {
        if (file_ind >= files.length){
            return;
        }

        const new_files = [...files];
        new_files.splice(file_ind, 1);

        set_files(new_files);
        inc_revision();
    }

// ...

    return <div className={container_css}
                onDragEnter={handle_add_area_drag_enter}
                onDragExit={handle_add_area_drag_exit}
                onDragOver={handle_add_area_drag_over}
                onDrop={handle_add_area_drop}
    >
        {files_dom}

        {/* Drop Area */}
        {show_drop_area? (
            <div className={add_area_css} onClick={handle_add_area_click}>
                {drop_area_message}
            </div>
        ) : null}

        <input type="file"
               multiple
               ref={file_input_ref}
               className={'hidden'}
               onChange={handle_input_file_change}
               autoComplete={'off'}
               key={'input_file_'+revision}
        />
    </div>

```

**Comment by GongT** [comment]
Cant find a way to forget files.

I have a infinity file drop zone, it:
1. receive a file
2. process the file
3. wait for next file

* if I set `multiple=false` then it can not wait for next file.
* if I set `multiple=true` then it can not reject file during processing.

I need a way to reset all internal state to initial state.
