### ISSUE TITLE
The default message not change

### ISSUE THREAD

**Issue by eugenio1590** [react-dropzone/react-dropzone#818]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
When I use the getFilesFromEvent function in the Dropzone component and I put a file in the "zone" it does not change the default message.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://codesandbox.io/s/x33nrprk3p?fontsize=14

**What is the expected behavior?**
When I put a file in the "zone" the message must change from "Drag and drop some images here, or {click} to select images" to "Drop the images here..."

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
The dependencies are:

"dependencies": {
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-dropzone": "10.1.3",
    "react-scripts": "2.1.8",
    "styled-components": "4.2.0"
  },
  "devDependencies": {
    "typescript": "3.3.3"
  },

**Comment by rolandjitsu** [comment]
@eugenio1590 if you're using your own getter for files, I'd advise checking out the following: https://github.com/react-dropzone/react-dropzone/blob/ea5fb32de4e5eb709f4f7d0851e8030addb5f6f4/src/utils/index.js#L29

You need to make sure it returns true during on drag enter and on drop.

I advise using our [default](https://github.com/react-dropzone/file-selector) getter which should be working just fine in most cases. Otherwise, you're on your own.
