### ISSUE TITLE
Single File Restriction

### ISSUE THREAD

**Issue by Yunustuzun** [react-dropzone/react-dropzone#845]
- [ ] I found a bug
- [X] I want to propose a feature

**What is the current behavior?**
Hello , 
I want restrict it to be selectable for one file ? I couldt find any parameter for it. If there isn't like this feature it can be propose also.

Also I use multiple parameter like this..

`<Dropzone onDropAccepted={this.onDropAccepted} accept='image/*' multiple="false">`

**Comment by wenhao-eb** [comment]
I have found that the 'multiple' prop only works when I select files from file dialog, it doesn't work when i directly drag and drop some files.

**Comment by rolandjitsu** [comment]
`multiple` works as expected in all tests. That is, it will reject all but a single file that you selected on drop. Whereas, if you click and open the select file window, it should only allow selecting one file.

I will close this for now unless you can provide an example illustrating an issue with the multiple attribute.

**Comment by irvingmoar** [comment]
Indeed, the attribute works as expected. But when I enter the parameters for `useDropzone({})` in the IDE, `multiple` does not appear in the auto-completion list, although the rest of the attributes are there. This is a bit confusing, which is why I got into this issue, thinking that the attribute is not supported.
