### ISSUE TITLE
IsDragReject evaluating to true even though no error were fired.

### ISSUE THREAD

**Issue by guylhermetabosa** [react-dropzone/react-dropzone#888]
**Do you want to request a *feature* or report a *bug*?**

- [ X] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Able to drop image but getting isDragReject true which leds to unexpected UI error treatments
https://codesandbox.io/s/wandering-tdd-ehs4e

**What is the expected behavior?**
Be able to drop an image and do not get isDragReject with truthy value.

**If this is a feature request, what is motivation or use case for changing the behavior?**
After investigation, I realized that this behavior was inserted by #878.

On this method 

`export function fileMatchSize(file, maxSize, minSize) {
  return file.size <= maxSize && file.size >= minSize;
}`

 file.size is undefined which leads to a falsy evaluation, and this file param is a DataTransferItem defined in here: [DataTransferItem ](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem), having only two read-only props, kind and type, maybe we should use getAsFile method in order to have access to file itself, but on my local it returns undefined.

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Browser Version: Chrome 77.0.3865.90
OS: Window 10 Pro
React Dropzone Version: 10.1.10

Thanks, let me know if I can help somehow.

**Comment by ManSleen** [comment]
I'm currently having this same problem. To fix it temporarily, I reverted to react-dropzone v10.1.9 and isDragReject seems to be working fine again.

**Comment by guylhermetabosa** [comment]
@ManSleen I've done the same thing.

**Comment by rolandjitsu** [comment]
During the drag operation you cannot get the file data (size, etc.), therefore, there is no reliable way to check the file size during drag.

But I think we can revert to the previous behavior and keep the behavior introduced by https://github.com/react-dropzone/react-dropzone/pull/878 by checking if the file size is undefined.

**Comment by carvalhoviniciusluiz** [comment]
I have the same problem, any correction prediction?

**Comment by blackr1234** [comment]
> During the drag operation you cannot get the file data (size, etc.), therefore, there is no reliable way to check the file size during drag.
> 
> But I think we can revert to the previous behavior and keep the behavior introduced by #878 by checking if the file size is undefined.

Agree, better revert the changes introduced in version `10.1.10` as it broke the core function(s) of this library.

**Comment by givionte** [comment]
Also confirming isDragRejected rings true everytime no matter the file size on the most recent version.

**Comment by guylhermetabosa** [comment]
> During the drag operation you cannot get the file data (size, etc.), therefore, there is no reliable way to check the file size during drag.
> 
> But I think we can revert to the previous behavior and keep the behavior introduced by #878 by checking if the file size is undefined.

Yeah, sounds as the best solution for now to me, I'll try to work on this on the weekend in order to try to get the file during drag operation.

**Comment by aaronbeall** [comment]
I'm seeing the same issue with `10.1.9` where I have `<Dropzone accept=".pod">`, the render function always receives `isDragReject=true` even though, upon drop, it successfully accepts a file like `foo.pod` and rejects a file like `foo.gif`.

**Comment by Popov85** [comment]
The issue remains in the scenario if I have `accept = ".txt,.png,.doc"` that is a list of comma-separated file extensions. With MIME types is works smoothly.

**Comment by nterol** [comment]
I'm having this same issue on accept `".jpg, .png, .svg"`.  It fails whatever is the extension of the file.

**Comment by NicolasZim** [comment]
> I'm having this same issue on accept `".jpg, .png, .svg"`. It fails whatever is the extension of the file.
> 
> > "react-dropzone": "^11.2.4", macOS 11.12, Chrome  88.0.4324.146

Having the same issue, with ```.rem``` and ```.ret``` files. Seems to me that's doesn't check the file extension. However i had read some issues that people was talking about being impossible to read file info until file drop into input.Tried to downgrade but still not working.

Any ideas? Hacks? Solutions?

Also `.rem, .ret` are mostly used in my country since they are files that banks use and request.

**Comment by ongopongo** [comment]
I'm seeing this issue with the latest version of `react-dropzone`.

```
react-dropzone@11.5.1
Google Chrome Version 97.0.4692.71 (Official Build) (x86_64)
macOS 11.5.2
```

I see the issue whether I set the `accept` prop to an array of strings (e.g. `[".p12"]`) or to a string (e.g. `".p12"`), where each string is a file extension (i.e. suffix) as opposed to a MIME type.

I don't understand why this Issue is still closed.

**Comment by dav92lee** [comment]
Seeing this issue with STLs on:

```
react-dropzone@10.2.2
macOS 12.0.1
```

**Comment by rolandjitsu** [comment]
> The issue remains in the scenario if I have `accept = ".txt,.doc,.docx"` that is a list of comma-separated file extensions. With MIME types it works smoothly.
> 
> > "react-dropzone": "^10.2.1", Windows 7, Chrome Version 79.0.3945.130 (Official Build) (64-bit)

@Popov85 @nterol @NicolasZim and others. Yes, that's expected. As in, we can only do MIME type validation during the drag operation, file extensions will not work until dropped (due to browsers not allowing it for security reasons). Even that may not work if the extension is not a known one (see [react-dropzone/file-selector/src/file.ts#L1](https://github.com/react-dropzone/file-selector/blob/8bf52d4d288825d292c0e0d25c46a5f734ba6700/src/file.ts#L1)).

The issue is closed because the original reported issue has been addressed.
