### ISSUE TITLE
isDrag style properties work with image/* but not with custom file extensions 

### ISSUE THREAD

**Issue by Angelixus** [react-dropzone/react-dropzone#953]
**Do you want to request a *feature* or report a *bug*?**

- [x] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
Using inline styles as described on the [project webpage](https://react-dropzone.js.org/) if the accept propert of the useDropzone() method is 'image/*' the inline styles work as expected (when the file is an image the border is green, otherwise is red) but with a custom file extension (e.g '.gpx') the border is always red regardless of the file extension.
**If the current behavior is a bug, please provide the steps to reproduce.**

1. Copy the code from the 'Using inline styles' section of the project webpage
1. Change the accept property on the useDropzone() method to accept : '.gpx'
1. Check that dragging a file whether it is .gpx or any other extension the border color is red.

**What is the expected behavior?**
That, using accept: '.gpx', the border of the drag and drop is green when a .gpx file is given and red otherwise.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Operating System and react-dropzone version.**
Checked on Google Chrome version 80.0.3987.149
react-dropzone version: 10.2.2

**Comment by gblanco10** [comment]
I comment here because the problem still exists. Here my testing environment :
- Chrome version : 90.0.4430.212
- react-dropzone version : 11.3.2
- react version 17.0.2 

I specified in the accept prop of useDropzone hook the type '.xls,.xlsx' but when I drag into the area excel files the isDragAccept property is always set to false and instead the isDragReject property is set to true. I followed the code example at https://react-dropzone.js.org/ in section 'Styling Dropzone - Using inline styles' but I do not obtain the same behaviour of the example unless I set the accept type as 'image/*' as in the example .
