### ISSUE TITLE
maxSize and mineSize not effect isDragAccept

### ISSUE THREAD

**Issue by yotavm** [react-dropzone/react-dropzone#960]
- [v] I found a bug
- [ ] I want to propose a feature

**What is the current behavior?**
1. added maxSize and minSize
2. when I drag file bigger or smaller the isDragAccept it's true so I see the green background
3. but when I drop the file noting happen 

**If the current behavior is a bug, please provide the steps to reproduce.**
this is the basic code
```
<Dropzone
          onDropAccepted={this.onDropAccepted}
          onDrop={acceptedFiles => console.log(acceptedFiles)}
          accept={'image/gif,image/jpg,image/jpeg,image/png,application/pdf'}
          style={{ border: 0, width: '100%' }}
          maxSize={2e7}
          minSize={1000}
        >
          {this.renderDropZoneDesign}
        </Dropzone>
```
renderDropZoneDesign
```
renderDropZoneDesign = ({
    getRootProps,
    getInputProps,
    isDragAccept,
    isDragReject,
    ...props
  }) => {
    console.log(getRootProps, getInputProps, isDragAccept, isDragReject, props);
    return (
      <div {...getRootProps({ style: { border: 0, width: '100%' } })}>
        <input {...getInputProps()} />
        <DropAndDragZone //style.componet change background according the props
          isDragAccept={isDragAccept}
          isDragReject={isDragReject}
        >
          {this.renderDropZoneLabel(isDragAccept, isDragReject)} //check with text to give
        </DropAndDragZone>
      </div>
    );
  };
```
the problem is that isDragAccept its true but the file its to big or to small
**What is the expected behavior?**
when i drag file that its to big or to small i went the user to see that he can't use this file

react-dropzone 10.2.2
using component and not hook

**Comment by SwinX** [comment]
Having the same issue with `isDragReject` - it's always set to false for files that exceed size limit. 
Able to reproduce on a version 11.0.1

**Comment by southernBuryatian** [comment]
_Drag_ events (excepting dragstart, which is triggered when user starts to drag an html element on a web page, which is not the case here) do not have access to file size or content by design - https://html.spec.whatwg.org/multipage/dnd.html#dndevents . Probably this is made to restrict visibility for accidentally dragged files. You can only decide if the file size fits on _drop_ event - which is implemented in react-dropzone fileRejections parameter, error codes for this are: 'file-too-small' and 'file-too-large'.
